export enum MonthPickerThemeVar {
  CALENDAR_ICON = '--month-picker-calendar-icon',
  CALENDAR_ICON_BACKGROUND = '--month-picker-calendar-icon-background',
  CALENDAR_ICON_BORDER = '--month-picker-calendar-icon-border',
  CALENDAR_ICON_BORDER_ACTIVE = '--month-picker-calendar-icon-border-active',
  CONTAINER_BORDER = '--month-picker-container-border',
  FONT_FAMILY = '--month-picker-font-family',
  MONTH_BUTTON_BACKGROUND_DESELECTED = '--month-picker-month-button-background-deselected',
  MONTH_BUTTON_BACKGROUND_SELECTED = '--month-picker-month-button-background-selected',
  MONTH_BUTTON_BACKGROUND_UNAVAILABLE = '--month-picker-month-button-background-unavailable',
  MONTH_BUTTON_TEXT_DESELECTED = '--month-picker-month-button-deselected',
  MONTH_BUTTON_TEXT_SELECTED = '--month-picker-month-button-selected',
  MONTH_BUTTON_TEXT_UNAVAILABLE = '--month-picker-month-button-unavailable',
  NAV_BUTTON_BACKGROUND = '--month-picker-nav-btn-background',
  NAV_BUTTON_BACKGROUND_DISABLED = '--month-picker-nav-btn-background-disabled',
  NAV_BUTTON_BORDER = '--month-picker-nav-btn-border',
  NAV_BUTTON_BORDER_HOVER = '--month-picker-nav-btn-border-hover',
  NAV_BUTTON_BORDER_HOVER_DISABLED = '--month-picker-nav-btn-border-hover-disabled',
  OVERLAY_BACKGROUND = '--month-picker-overlay',
  VISIBLE_MONTH_PICKER_BACKGROUND = '--month-picker-visible-picker-background',
  YEAR_ROW_BACKGROUND = '--month-picker-year-row-background',
}
